import Image from 'next/image';
import { BatteryCharging, Car, CheckCircle2, ChevronDown, House, Leaf, Menu, PlugZap, ShieldCheck, ShoppingCart, Sun, Truck, Wrench, Zap } from 'lucide-react';
const products=[['Pulse Home','11 kW','Okos fali töltő','189 900 Ft'],['Volt Pro','22 kW','Wi-Fi • Type 2','239 900 Ft'],['GoCharge','7,4 kW','Hordozható','99 900 Ft'],['Solar Sync','11 kW','Napelem-ready','219 900 Ft']];
export default function Home(){return <main>
<header className="header"><a className="brand" href="#"><span className="brandIcon"><Zap size={25}/></span><span><b>Töltés<span>Otthon</span></b><small>TISZTA ENERGIA. BIZTOS JÖVŐ.</small></span></a><nav><a href="#tolto">Töltők</a><a href="#valaszto">Autóhoz ajánlott</a><a href="#telepites">Telepítés</a><a href="#solar">Napelemes töltés</a><a href="#tudastar">Tudástár</a></nav><div className="actions"><ShoppingCart size={21}/><button className="mobile"><Menu/></button></div></header>
<section className="hero"><Image className="heroImage" src="/hero-ev-home.webp" alt="Elektromos autó otthoni fali töltővel" fill priority sizes="100vw"/><div className="heroShade"></div><div className="heroContent"><div className="eyebrow"><Zap size={16}/> Töltés egyszerűen, otthon</div><h1>Otthoni és üzleti<br/>elektromos autó töltők<br/><em>egy helyen</em></h1><p>Megbízható töltési megoldások, szakértői támogatással és országos telepítéssel.</p><div className="heroButtons"><a className="btn" href="#valaszto">Találd meg a megfelelő töltőt <span>→</span></a><a className="btn ghost" href="#telepites">Ajánlatkérés telepítéssel</a></div><div className="benefits"><span><Truck/> Gyors kiszállítás</span><span><ShieldCheck/> Garancia</span><span><Wrench/> Országos telepítés</span><span><Leaf/> Napelemes megoldások</span></div></div></section>
<section id="valaszto" className="selector wrap"><div><h2>Milyen autód van?</h2><p>Segítünk megtalálni a számodra megfelelő töltőt néhány egyszerű lépésben.</p></div><div className="selectGrid"><button><Car/> Autómárka <ChevronDown/></button><button><BatteryCharging/> Modell <ChevronDown/></button><button><House/> Otthoni töltés <ChevronDown/></button><button className="btn">Mutasd az ajánlott töltőket →</button></div></section>
<section id="tolto" className="wrap section"><div className="sectionHead"><div><span className="kicker">MEGOLDÁSOK MINDEN HELYZETRE</span><h2>Termékkategóriák</h2></div><a>Összes kategória →</a></div><div className="categories"><article><House/><h3>Fali töltők</h3><p>Otthonra és üzleti használatra</p><b>Megnézem →</b></article><article><PlugZap/><h3>Hordozható töltők</h3><p>Utazáshoz, rugalmas használatra</p><b>Megnézem →</b></article><article><Zap/><h3>Töltőkábelek</h3><p>Type 2 kábelek többféle hosszban</p><b>Megnézem →</b></article><article><ShieldCheck/><h3>Kiegészítők</h3><p>Tartók, oszlopok, kártyák és védelem</p><b>Megnézem →</b></article></div></section>
<section className="wrap section"><div className="sectionHead"><div><span className="kicker">VÁLOGATOTT AJÁNLATOK</span><h2>Népszerű termékek</h2></div><div className="chips"><span>Összes</span><span>7,4 kW</span><span>11 kW</span><span>22 kW</span></div></div><div className="products">{products.map((p,i)=><article key={p[0]}><div className="productVisual"><div className={'miniCharger c'+i}><Zap/></div>{i===0&&<label>Népszerű</label>}</div><small>{p[2]}</small><h3>{p[0]}</h3><p>{p[1]} • Type 2</p><div className="price"><b>{p[3]}</b><button><ShoppingCart size={18}/></button></div><span className="stock">● Raktáron</span></article>)}</div></section>
<section className="split wrap section"><article id="solar" className="feature dark"><Sun/><span>NAPELEM + AUTÓTÖLTÉS</span><h2>Napelemes töltés<br/>otthonra és üzletre</h2><p>Használd a saját napelemed energiáját az autód töltésére.</p><a className="btn">Tudj meg többet →</a></article><article id="telepites" className="feature light"><Wrench/><span>TELJES KÖRŰ KIVITELEZÉS</span><h2>Telepítés<br/>országosan</h2><p>Felmérés, tanácsadás, kivitelezés és garancia egy kézből.</p><a className="btn">Kérek ajánlatot →</a></article></section>
<section id="tudastar" className="wrap section"><div className="sectionHead"><div><span className="kicker">SEGÍTÜNK DÖNTENI</span><h2>Tudástár</h2></div><a>Összes cikk →</a></div><div className="articles"><article><Zap/><h3>11 vagy 22 kW-os töltő?</h3><p>Melyik a jobb választás otthonra?</p></article><article><Sun/><h3>Napelemes autótöltés</h3><p>Hogyan használd a saját energiád?</p></article><article><Car/><h3>Milyen töltőt válasszak?</h3><p>Autó alapján segítünk dönteni.</p></article></div></section>
<footer><div className="wrap footer"><div className="brand"><span className="brandIcon"><Zap size={22}/></span><span><b>Töltés<span>Otthon</span></b><small>TISZTA ENERGIA. BIZTOS JÖVŐ.</small></span></div><p>Elektromos autó töltési megoldások egyszerűen.</p><small>© 2026 TöltésOtthon</small></div></footer>
</main>}
